language: cpp

install:
  # Pip cannot install Conan without these upgrades
  - python3 -m pip install --upgrade pip setuptools
  # Install Conan and CMake >= 3.15
  - python3 -m pip install conan cmake

  # Fail if we can't run Conan.
  - conan --version

jobs:
  include:
    # can't find gcc-10.0
    - os: osx
      compiler: gcc-10
      osx_image: xcode12.2    # includes which gcc by default?
      env:
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
      addons:
        homebrew:
          packages:
          - gcc@10
    
    # got the correct version, but still barfs including concepts header
    # Apple clang is apparently behind and doesn't have concepts yet. 
    - os: osx
      compiler: clang-12.0
      osx_image: xcode12.2

    
    - os: linux
      dist: focal
      compiler: gcc
      env:
        - GCC_VER="10"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"

      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # I couldn't get ${GCC_VER} in here successfully
            - gcc-10
            - g++-10
            - doxygen
            - python3-pip
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}

    # clang 10 is default on focal
    # https://docs.travis-ci.com/user/reference/focal/#compilers-and-build-toolchain
    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            #- llvm-toolchain-focal-10.0 # needed?
          packages:
            - clang-10.0
            - doxygen
            - python3-pip
      env:
        - MATRIX_EVAL="CC=clang-10.0 && CXX=clang++-10.0"


before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE ../
  - cmake --build . -- -j2
  - ctest -j2



